### PR TITLE
Make path to bundle optional

### PR DESCRIPTION
**Pull request by hqhq**
Make it optional looks reasonable to me, and it's what
we do in runc now.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
On Mon, May 23, 2016 at 02:31:56AM -0700, Qiang Huang wrote:
> Make it optional looks reasonable to me, and it's what we do in runc
> now.

These sketches are not intended to be a command-line API [1].  I think
this change would be useful in a command-line API document, but is
probably too detailed for the operation overview here (where “the
runtime needs to know which config to use” is all you need to
express).

[1]: https://github.com/opencontainers/runtime-spec/pull/225#issuecomment-172626408

**Comment by crosbymichael** [comment]
@hqhq i think this is just an error in the docs, it is a flag on the runtime and has always been a flag.  I think its safe to just remove this for now as it was never the case.

**Comment by wking** [comment]
On Mon, May 23, 2016 at 12:57:55PM -0700, Michael Crosby wrote:
> I think its safe to just remove this for now as it was never the
> case.

What was never the case?  The runtime does need to know which
bundle/config it's starting.  For runC, it can get a reasonable
default by using getcwd(3), but that won't be a reasonable default for
all runtimes (e.g. if your runtime API is via HTTP web requests, the
web-server's CWD is probably not interesting).  The ‘start’ operation
needs more information here than, say, the ‘state’ operation, so I
think it makes sense to list that extra information here.

**Comment by crosbymichael** [comment]
Oh, I see.  This is not specifying a CLI but just specifying the inputs to the start action.  If we look at it that way then bundle path is required even though most runtimes will imply the bundle path is the `cwd` but for the start action it is a required input.

**Comment by wking** [comment]
On Mon, May 23, 2016 at 01:15:23PM -0700, Michael Crosby wrote:
> This is not specifying a CLI but just specifying the inputs to the
> start action.  If we look at it that way…

That's how I've been looking at it based on [1], but a few folks have
interpreted these as a CLI API now, so it's probably worth explicitly
saying that they aren't in the spec.  I can file a separate PR to that
effect tonight.

[1]: https://github.com/opencontainers/runtime-spec/pull/225#issuecomment-172626408

**Comment by hqhq** [comment]
@wking It make sense if it's input for general operation, I already opened a PR https://github.com/opencontainers/runtime-spec/pull/450 to clarify this, PTAL, thanks.

**Pull request closed without merging**
