### PR TITLE
Makefile: comment on seemingly unused variable

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by wking** [comment]
SHELL was added in f3fdf03a (Makefile: prefer bash, 2016-05-25, #455)
referencing #454.  I am in favor of a Makefile that only needs a POSIX
shell, but I'd like to understand any POSIX-shell-incompatibilities.
I would have preferred to have that information before we added the
variable [1], but I guess I'm ok removing it, waiting for someone to
reopen #454, and then collecting that information before re-adding
SHELL (or ideally, fixing the POSIX-shell-incompatible command).

[1]: https://github.com/opencontainers/runtime-spec/issues/454#issuecomment-221598064

**Comment by vbatts** [comment]
Oh oh oh
This commit should instead be.... A comment

**Comment by vbatts** [comment]
updated PTAL

**Comment by wking** [comment]
I'd rather just fix the POSIX-compatiblity issue, instead of working
around it.  Fix filed in #542.

**Pull request closed without merging**
