### PR TITLE
Transition from Markdown to AsciiDoc

### PR DESCRIPTION
**Pull request by wking**
As discussed in #615.  Rendered HTML and PDF forms are [here][1] and [here][2].  There's a fair bit of detail in most commit messages if you're interested in that sort of thing.

The base of this PR is currently a few commits behind master, but keeping this branch up do date will be a pain.  I think we should collect feedback on the approach here, and if/when the approach collects enough maintainer approval I'll push through a rebase and we can land this quickly (before it goes stale again, which will happen if pretty much anything touching the Markdown lands ;).

[1]: http://wking.github.io/opencontainer-runtime-spec/
[2]: http://wking.github.io/opencontainer-runtime-spec/runtime-spec.pdf

### CODE REVIEW

**Comment by wking** [comment]
CC @vbatts, @RobDolinMS.

**Comment by mrunalp** [comment]
The rendered pdf/html look pretty good!

**Comment by mrunalp** [comment]
@wking Sorry I missed this PR earlier. I agree that if everyone is on board, we should land this first.

**Comment by duglin** [comment]
can we do this after https://github.com/opencontainers/runtime-spec/pull/626  ?

**Comment by wking** [comment]
On Tue, Nov 15, 2016 at 12:20:20PM -0800, Doug Davis wrote:
> can we do this after
> https://github.com/opencontainers/runtime-spec/pull/626 ?

Sure.  I'm happy to rebase around anything that lands before this PR.
I'd just rather not have to rebase this one multiple times ;).

**Comment by duglin** [comment]
that's how I feel too :-)

**Comment by dqminh** [comment]
The rendered version looks good ( like really good compared to markdown-rendered :smile: )

**Comment by mrunalp** [comment]
could be rebased now that #626 is merged.

**Comment by wking** [comment]
On Wed, Nov 16, 2016 at 12:19:06PM -0800, Mrunal Patel wrote:
> could be rebased now that #626 is merged.

There are still a lot of open PRs that would conflict with this one
(e.g. #620, #611, #607, #606, #577, …).  Before we rebase this to
worry about content, I'd rather hash out any content-agnostic
technical issues.  Once we have some maintainers approving the
technical approach, I'll rebase to bring the content up to speed and
we can collect official LGTMs on the whole package.

**Comment by hqhq** [comment]
I'm +1 for this change, rendered version looks better than markdown.

**Comment by RobDolinMS** [comment]
Per @crosbymichael, not sure we want to do this at all; but agree we want to hold-off on this conversation until after v1.0.0

**Comment by crosbymichael** [comment]
We will looking into consolidating the spec into a single markdown file to make publishing easier.

**Comment by vbatts** [comment]
there will be pains in either staying with markdown or switching to asciidoc

**Pull request closed without merging**
