### PR TITLE
.travis: Convert TRAVIS_COMMIT_RANGE base...head to base..head

### PR DESCRIPTION
**Pull request by wking**
Work around travis-ci/travis-ci#4596 until that is fixed upstream.
This avoids pulling in commits from the base tip that aren't reachable
from the head tip (e.g. if master has advanced since the PR branched
off, and the PR is against master).  We only want to check commits
that are in the head branch but not in the base branch (more details
on the range syntax [here](http://git-scm.com/docs/gitrevisions#_specifying_ranges)).

Once the Travis bug does get fixed, the shell replacement will be a
no-op.  So we don't have to worry about checks breaking once the bug
gets fixed, and can periodically poll the bug and remove the
workaround at out leisure after the fix.

Spun off from #182 now that #215 has landed.

### CODE REVIEW

**Comment by vbatts** [comment]
is this really an issue to us?

**Comment by wking** [comment]
On Mon, Jan 04, 2016 at 10:39:14AM -0800, Vincent Batts wrote:
> is this really an issue to us?

It's only an issue if there are broken commits in the master branch.
We seem to have avoided that so far, with the only merged failure
being the (Travis hiccup?) [1,2].  So not a critical fix, but still
something that I think is worth landing.

[1]: https://travis-ci.org/opencontainers/specs/builds/86717595
[2]: https://github.com/opencontainers/specs/pull/227#event-442027245

**Comment by vbatts** [comment]
as this has not impacted us, and may not for some foreseeable future, I'm inclined to close it. It could always be reopened if the need be.

**Comment by cyphar** [comment]
Time to reopen I guess.

**Comment by vbatts** [comment]
@cyphar what is needing the reopening?

**Comment by wking** [comment]
On Mon, Jul 25, 2016 at 11:54:45AM -0700, Vincent Batts wrote:
> @cyphar what is needing the reopening?

#520 was reporting errors in old master commits [1], but its
replacement #521 did not.  So you can probably re-close this and kick
the can down the road again ;).

[1]: https://github.com/opencontainers/runtime-spec/pull/520#issuecomment-234597864

**Comment by vbatts** [comment]
:confused:

**Comment by wking** [comment]
On Mon, Jul 25, 2016 at 12:02:13PM -0700, Vincent Batts wrote:
> :confused: 

I still think this is a useful change, and could land now.  You
(presumably) still think we should wait until we are impacted by not
landing it [1].  We may have been impacted by it in #520 [2], but
that's no longer open.  So we're back to “no currently open PRs are
impacted by this not being merged”, and the last time we were there
you closed the PR [1].

[1]: https://github.com/opencontainers/runtime-spec/pull/216#issuecomment-171473542
[2]: https://github.com/opencontainers/runtime-spec/pull/520#issuecomment-234597864

**Comment by vbatts** [comment]
lets give this a try. could you rebase?

**Comment by wking** [comment]
On Wed, Jan 18, 2017 at 02:09:01PM -0800, Vincent Batts wrote:
> lets give this a try. could you rebase?

Rebased with d815fa9 → 40035db.

**Comment by wking** [comment]
I fixed up passing the environment variable through to git-validation
and shifted the base of the branch back a few commits for testing with
40035db → d9b7bc3.  That leaves Travis testing a history like:

  $ git log --graph --decorate --oneline origin/master wking/travis-test-branch-commits
  *   995c556 (HEAD) Merge d9b7bc3 into c368be6
  |\  
  | * d9b7bc3 (wking/travis-test-branch-commits, origin/pr/216) .travis: Convert TRAVIS_COMMIT_RANGE base...head to base..head
  * |   c368be6 (origin/master, origin/HEAD) Merge pull request #650 from wking/readme-header-nesting
  |\ \  
  | * | 200e86f (origin/pr/650) README: Consistent header nesting
  * | |   dc0fa75 Merge pull request #655 from Mashimiao/schema-fix-with-latest-spec
  |\ \ \  
  | |_|/  
  |/| |   
  | * | 5076439 (origin/pr/655) schema: fix items based on latest spec
  * | |   937ea7b Merge pull request #490 from wking/json-schema-validate-http-schema
  … … …

Travis is setting the buggy three-dot form (c368be6a...d9b7bc39 [1]),
which includes all the commits not reachable from both commits:

  $ git log --oneline c368be6a...d9b7bc39
  d9b7bc3 .travis: Convert TRAVIS_COMMIT_RANGE base...head to base..head
  c368be6 Merge pull request #650 from wking/readme-header-nesting
  dc0fa75 Merge pull request #655 from Mashimiao/schema-fix-with-latest-spec
  5076439 schema: fix items based on latest spec
  200e86f README: Consistent header nesting

This PR fixes that so git-validation is called with the two-dot form,
which includes only the unique-to-this-PR commit:

  $ git log --oneline c368be6a..d9b7bc39
  d9b7bc3 .travis: Convert TRAVIS_COMMIT_RANGE base...head to base..head

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/193276777#L292

**Comment by wking** [comment]
I've also brought over the new commits from opencontainers/image-spec#521, which should help with failures from local-branch PRs  (e.g. [here][1] for #661).

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/193148311#L285

**Comment by vbatts** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
