### PR TITLE
maintainer updates as per #1101

### PR DESCRIPTION
**Pull request by h-vetinari**
Add "recently" added runc-maintainers also to runtime spec (emails taken from [runc](https://github.com/opencontainers/runc/blob/main/MAINTAINERS)). These 3 have a proven track record of excellent work in runc, and so I feel comfortable to propose them as one batch.

They have also all agreed in #1101 to join, see [this comment](https://github.com/opencontainers/runtime-spec/issues/1101#issuecomment-916972654) and below.

If someone wants to split the PR or propose their own one, I really really don't mind - I'm just trying to get the ball rolling. 🙃 

CC @AkihiroSuda 
CC @kolyshkin 
CC @thaJeztah 

Needs at least 6 approvals from the current 8 maintainers:
* [ ] crosbymichael 
* [x] cyphar 
* [ ] dqminh 
* [x] giuseppe 
* [x] hqhq 
* [x] mrunalp 
* [x] tianon 
* [ ] vbatts

### CODE REVIEW

**Review by kolyshkin — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
Thanks, LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by samuelkarp** [comment]
Hey folks!

I wanted to chime in from the TOB here.  It looks like the [governance document](https://github.com/opencontainers/runtime-spec/blob/main/GOVERNANCE.md) for the runtime spec does not currently establish procedures for adding (or removing) maintainers.  Under the current set of rules I can see two paths forward:

1. Amend the governance document per the process outlined there (motion and voting on the dev@opencontainers.org mailing list) to add rules around how maintainers can be added (or removed).
2. Or, directly move to add the new maintainers via a single vote using the same process.  Note that this path doesn't address the general case of establishing rules around how maintainers are added (or removed) and eventually we'll likely need to revisit that again.

The current governance rules require a 2/3 approval for a motion to pass; with 8 current maintainers that means at least 6 must approve.

(Note: the governance document recommends voting on the mailing list with a "SHOULD" but not a "MUST" so I think it'd be reasonable to go forward with 6 approvals here _if_ the current maintainers prefer to do that.)

Thanks!
Sam

**Review by hqhq — APPROVED** [review]

**Comment by h-vetinari** [comment]
PTAL @crosbymichael @cyphar @dqminh @mrunalp @tianon @vbatts

**Review by mrunalp — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Review by cyphar — APPROVED** [review]
LGTM

**Comment by cyphar** [comment]
@samuelkarp I don't know why it's not mentioned in the governance document (the point of copy-pasting the same document was so we had rules for everything already), but adding maintainers with a 2/3rd vote is accepted practice and is covered under the general governance change rules. It would be a good idea to do a review of the governance documents for all the projects to make sure they aren't missing important information like this.

I suspect this information is missing because the rules for adding maintainers in runc were outlined in the `MAINTAINERS_GUIDE.md` rather than `GOVERNANCE.md` but runtime-spec didn't copy the former into this repo.

**Comment by h-vetinari** [comment]
> Gentle ping @crosbymichael @dqminh @vbatts

☝️

**Review by vbatts — APPROVED** [review]
LGTM

Sorry I missed this PR. And then came here as I'm trying to determine and refresh myself on the process for adding and removing maintainers :-\

I generally agree with maintaining the 2/3 quorum for topics like adding/removing maintainers. And hope to see (or create) a PR for this language in the specs projects soon.

For the record, with my vote it makes the 2/3 quorum for _this_ vote. And effective upon merge we'll have **11** maintainers for an 7.3 majority? So, A) maybe we'll round that to 7?; B) perhaps some folks step down before being voted off?

**Comment by vbatts** [comment]
congrats and welcome @AkihiroSuda, @kolyshkin, and @thaJeztah! :cupcake:

**Pull request merged**
