### PR TITLE
[Runtime] Bump ociVersion in example

### PR DESCRIPTION
**Pull request by RobDolinMS**
Updates from 0.2.0 to 1.0.0 

Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Mar 15, 2017 at 03:16:30PM -0700, Rob Dolin (MSFT) wrote:
> Updates from 0.2.0 to 1.0.0 

If we're doing this (which is fine with me), you'll probably also want
to get these [1,2].  Although those can obviously happen in a separate
PR if you want.

[1]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L25
[2]: https://github.com/opencontainers/runtime-spec/blame/v1.0.0-rc5/config.md#L446

**Comment by wking** [comment]
I'm not sure why git-validation is exiting 128 (or complaining about
Git exiting 128?) [1].  I can't reproduce that locally.  @vbatts, any
ideas?

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/211537769#L323

**Comment by hqhq** [comment]
I don't feel it's needed, especially before 1.0 is really landed, I'll close for now and remove the branch in upstream, feel free to open a new PR when this change it suitable.

**Comment by wking** [comment]
On Wed, Mar 29, 2017 at 11:28:52PM -0700, Qiang Huang wrote:
> I don't feel it's needed, especially before 1.0 is really landed…

With the 1.0 vote scheduled for the recent past (#726), I think now is
the right time for this.  If you want the change to be part of the 1.0
docs (which I think we do), it needs to land before the 1.0 tag.

**Comment by hqhq** [comment]
It's an example and I don't feel it must be landed before 1.0, but I won't object if others want to, since this PR creates branch on upstream repo and didn't change all version examples, @RobDolinMS do you mind opening an new PR if you still want to do this?

Remember to click the `Fork` button in the upper-right corner to create your own fork and create branches there, thanks.

**Comment by wking** [comment]
> It's an example and I don't feel it must be landed before 1.0…

Should we reopen this (and also fix [the other stale versions][1]?), since #881 landed recently with a similar change?

[1]: https://github.com/opencontainers/runtime-spec/pull/727#issuecomment-286898754

**Pull request closed without merging**
