### PR TITLE
schema/state.json: Add a JSON Schema for the state JSON

### PR DESCRIPTION
**Pull request by wking**
Make it easy for folks to validate state JSON the same way they can
currently validate config.json.

This is spun off from #453, and I've left the config-oriented IDs
alone (with their /schema/bundle/… IDs) to avoid pulling in that
rejected adjustment.

### CODE REVIEW

**Comment by vbatts** [comment]
I know you've mentioned your opinion on the redundancy of 'schema' in the filename, but I'm holding to that. Even in the image spec, for multiple schemas, they are named `config-schema.json`, `image-manifest-schema.json` and `manifest-list-schema.json`

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 05:18:00AM -0700, Vincent Batts wrote:
> I know you've mentioned your opinion on the redundancy of 'schema'
> in the filename, but I'm holding to that. Even in the image spec,
> for multiple schemas, they are named `config-schema.json`,
> `image-manifest-schema.json` and `manifest-list-schema.json`

I don't see the point, but it's fine with me [1].  Is that just for
entrypoint JSON, or do you also want config-linux-schema.json,
defs-schema.json, etc.?

[1]: https://github.com/opencontainers/runtime-spec/pull/313#discussion_r55576244

**Comment by vbatts** [comment]
The defs* files are not schema particularly themselves. I'm fairly confident that it isn't just my own opinion of logical file naming, that the schema files to validate against, would actually have 'schema' in the name. All other files would be sourced as needed.

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 10:29:45AM -0700, Vincent Batts wrote:
> The defs* files are not schema particularly themselves.

The current schema-linux.json is also not a stand-alone schema.

> … the schema files to validate against, would actually have 'schema'
> in the name.

That sounds like “only use -schema for entrypoint files” [1].  I'll
reroll to use config-linux.json, config-solaris.json, config-schema.json,
defs-linux.json, defs.json, and state-schema.json.

[1]: https://github.com/opencontainers/runtime-spec/pull/481#issuecomment-223296169

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 11:20:05AM -0700, W. Trevor King wrote:
> On Fri, Jun 03, 2016 at 10:29:45AM -0700, Vincent Batts wrote:
> > … the schema files to validate against, would actually have
> > 'schema' in the name.
> 
> That sounds like “only use -schema for entrypoint files” [1].  I'll
> reroll to use config-linux.json, config-solaris.json,
> config-schema.json, defs-linux.json, defs.json, and
> state-schema.json.

Rerolled with ef4c6b0 → b4bcddb, which also rebases onto master
(around #482) and makes a few schema/README.md changes to more generic
language.

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
for reference, could provide a pastebin or gist to the state.json you were testing against?

**Comment by wking** [comment]
On Mon, Jun 06, 2016 at 07:48:21AM -0700, Vincent Batts wrote:
> for reference, could provide a pastebin or gist to the state.json
> you were testing against?

I was just using the spec's example [1], although it looks like I need
to reroll to pickup #484 (so don't merge this yet ;).

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc1/runtime.md#state

**Comment by wking** [comment]
On Mon, Jun 06, 2016 at 08:49:55AM -0700, W. Trevor King wrote:
> … it looks like I need to reroll to pick up #484…

Rerolled with b4bcddb → 8f67a50.

**Comment by crosbymichael** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/runtime-spec/pull-request/481/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/runtime-spec)

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
rebase please

**Comment by wking** [comment]
On Wed, Jun 08, 2016 at 08:16:49PM -0700, Vincent Batts wrote:
> rebase please

Rebased around #491 with 8f67a50 → 2a5986f.

**Comment by vbatts** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
