### PR TITLE
Add a working call-in number

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by wking** [comment]
UberConference has been working when @mrunalp is around; are we sure
we want to completely replace it?  I like being able to see who's
talking when I can't recognize someone's voice.

If we do remove it, we'll want to remove the remove the reference link
too [1].

[1]: https://github.com/duglin/runtime-spec/blame/e43c75b33f24eea1076ab53515bf5b9207025c7d/README.md#L165

**Comment by caniszczyk** [comment]
Sorry I should have got back sooner.

At the LF we created a line for OCI now, you're welcome to use that one:

Join the call: https://www.uberconference.com/opencontainers
Optional dial in number: 888-587-9088
Alternate number: 860-706-8529
No PIN needed

**Comment by duglin** [comment]
@caniszczyk thanks! I updated the PR to align with the info you provided.

**Comment by mrunalp** [comment]
Thanks!

**Comment by mrunalp** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
this should be mirrored in the image-spec and templates

**Comment by duglin** [comment]
@vbatts will try to do so later today....

**Comment by duglin** [comment]
found a ref in image-spec but not templates

**Pull request merged**
