### PR TITLE
schema: modify Makefile

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao zhouhao@cn.fujitsu.com

### CODE REVIEW

**Comment by hqhq** [comment]
I don't think it's necessary and it'll make the help information non-accurate.

Rejected.

**Comment by vbatts** [comment]
I don't see that it makes the help info incorrect. I'm two-ways about the default make target being `help`. Honestly, most of the time I expect the default target to be sensible, like building the tool or running the tests.
This PR LGTM in that sense

**Comment by hqhq** [comment]
@vbatts Not that incorrect, just not completely accurate.
```
$ make
Usage: make <target>

 * 'fmt' - format the json with indentation
 * 'validate' - build the validation tool
```
To me it means "make needs an target, which can be fmt or validate", if we make validate default and target is optional, I would like to see something like:
```
$ make
Usage: make [target]

 * 'fmt' - format the json with indentation
 * 'validate' - build the validation tool (default)
 * 'help' - show this help information
```

I'm also fine with changing the default target to be running the tests, just needs to fix help information as well.

**Comment by vbatts** [comment]
@hqhq oh oh, good catch. so yes, using square brackets there would be more accurate :smile_cat:

**Comment by q384566678** [comment]
@hqhq Thanks for your advice, update, PTAL.

**Comment by hqhq** [comment]
LGTM

**Comment by q384566678** [comment]
@vbatts @mrunalp @titanous PTAL

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
