### PR TITLE
*: specs -> runtime-spec

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by wking** [comment]
Everything through f6e82a97 looks good to me, although “Open Container
Runtime Specification” might be a more compact way to convey the same
idea.

**Comment by vbatts** [comment]
bumped the wording just a little. PTAL.

**Comment by wking** [comment]
On Mon, Apr 04, 2016 at 01:20:27PM -0700, Vincent Batts wrote:
> bumped the wording just a little. PTAL.

f6e82a9 → 04890d6 looks good to me, but in [1] I was talking about the
title.

[1]: https://github.com/opencontainers/runtime-spec/pull/365#issuecomment-205468389

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
I like @wking suggestion of "Open Container Runtime Specification" as the title.

**Comment by vbatts** [comment]
updated

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
