### PR TITLE
Forbid duplicated rlimits with same type

### PR DESCRIPTION
**Pull request by hqhq**
Alternative of #583 , as what we do for `namespaces`
in #597 .

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Nov 02, 2016 at 07:15:57PM -0700, Qiang Huang wrote:
> Alternative of #583 , as what we do for `namespaces`
> in #597 .

The concern with using objects for namespaces was the path handling
[1] (and I *still* think it would have been better to use an object
there [2]).  But we require at least one limit for rlimit entries
(otherwise what's the point?), so I don't see a reason to *not* go
with an object for rlimits.

[1]: https://github.com/opencontainers/runtime-spec/pull/598#issuecomment-257481007
[2]: https://github.com/opencontainers/runtime-spec/pull/597#issuecomment-256678568

**Comment by wking** [comment]
On Wed, Nov 02, 2016 at 08:36:27PM -0700, W. Trevor King wrote:
> But we require at least one limit for rlimit entries (otherwise
> what's the point?)…

Actually, we don't.  But an rlimit entry with neither hard nor soft is
a no-op, while in #598 we needed to distinguish between no-op and
“create a new namespace”.  So I think my initial “so I don't see a
reason to *not* go with an object for rlimits” still stands.

**Comment by hqhq** [comment]
@wking I still don't see the problem of using array here after we fix the duplicated type issue.

**Comment by wking** [comment]
It's nothing insurmountable, but add-or-replace and removal are much easier with objects.  In #597 I [linked][1] to [this hoop jumping][2] you need to support then for arrays.

[1]: https://github.com/opencontainers/runtime-spec/pull/597#issuecomment-256678568
[2]: https://github.com/opencontainers/runtime-tools/blob/389c73a0b20576b201a655c1ef37f5558f8ff64e/generate/generate.go#L777-L813

**Comment by crosbymichael** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
