### PR TITLE
config-windows: fix the type of maximum

### PR DESCRIPTION
**Pull request by q384566678**
https://github.com/opencontainers/runtime-spec/blame/master/specs-go/config.go#L459
https://github.com/opencontainers/runtime-spec/blame/master/schema/config-windows.json#L43

Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

**Comment by dqminh** [comment]
LGTM

**Comment by wking** [comment]
This PR now has two LGTMs and no pushback.  Can we merge it into master?  Are we waiting for more maintainers to chime in in case the change does turn out to be contentious?  Are we waiting until we settle on a [post-1.0 branching strategy][1] (this [seems like a patch-level bump][2] regardless of [what APIs SemVer covers][3]?  Something else?

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/9zZKpptGLSw
[2]: https://groups.google.com/a/opencontainers.org/d/msg/dev/_pvFMQN1DUM/F_FcgfpCBwAJ
[3]: https://groups.google.com/a/opencontainers.org/d/msg/dev/_pvFMQN1DUM/wIko_3VJBwAJ

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
