### PR TITLE
[ Configuration | Version ] Capitalize MUST

### PR DESCRIPTION
**Pull request by RobDolinMS**
"must" --> "MUST" (to clarify this is a requirement per RFC 2119)

Signed-off-by: Rob Dolin <RobDolin@microsoft.com>

### CODE REVIEW

**Comment by RobDolinMS** [comment]
Signed-off-by: Rob Dolin <RobDolin@microsoft.com>

**Comment by wking** [comment]
On Tue, Apr 26, 2016 at 05:57:49PM -0700, Rob Dolin (MSFT) wrote:
“"must" --> "MUST" (to clarify this is a requirement per RFC 2119)”

5455a0aa looks good to me.

**Comment by vbatts** [comment]
commit is not DCO signed

**Comment by RobDolinMS** [comment]
Will close and re-open.

**Comment by RobDolinMS** [comment]
Replaced by PR #409

**Pull request closed without merging**
