### PR TITLE
Bump version 1.0.0 rc2

### PR DESCRIPTION
**Pull request by vbatts**
https://groups.google.com/a/opencontainers.org/d/msg/dev/5qj2hATVxew/T9xFOcO-EAAJ

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Sep 07, 2016 at 07:27:00PM -0700, Vincent Batts wrote:
>   * ChangeLog: Document changes since v1.0.0-rc1
>   * version: bump version to 1.0.0-rc2

This is missing a non-dev version commit like 06479209b from #486.

**Comment by vbatts** [comment]
fixed

**Comment by wking** [comment]
769176bb looks good to me.  And just for clarity, we'll be tagging
7dab1a24.

**Comment by philips** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/runtime-spec/pull-request/557/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/runtime-spec)

**Comment by tianon** [comment]
As clarified on IRC, we're waiting for the vote to settle before considering merging this. :+1:

**Comment by tianon** [comment]
For reference, new vote is at https://groups.google.com/a/opencontainers.org/d/topic/dev/KIMfn6ucrsg/discussion

**Pull request merged**
