### PR TITLE
Add governance and release process docs

### PR DESCRIPTION
**Pull request by caniszczyk**
https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/x-Oh3PDz1Y8

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
Looks good to me:

  $ (cd runtime-spec && git --no-pager log -1 --oneline origin/pr/521 && git ls-tree origin/pr/521 GOVERNANCE.md RELEASES.md)
  6cf3cf3 Add governance and release process docs
  100644 blob 59c00bbc9bfd2d5255ff648aa478aa6662f4a1f0    GOVERNANCE.md
  100644 blob e220042c89008275b86f44c967983675f39f968e    RELEASES.md
  $ (cd project-template && git --no-pager log -1 --oneline origin/pr/15 && git ls-tree origin/pr/15 GOVERNANCE.md RELEASES.md)
  56abe12 GOVERNANCE and RELEASES: split the files
  100644 blob 59c00bbc9bfd2d5255ff648aa478aa6662f4a1f0    GOVERNANCE.md
  100644 blob e220042c89008275b86f44c967983675f39f968e    RELEASES.md

**Comment by cyphar** [comment]
LGTM, as discussed on the mailing list.

**Comment by wking** [comment]
On Fri, Jul 22, 2016 at 08:25:01PM -0700, Aleksa Sarai wrote:
> LGTM, as discussed on the mailing list.

I'm fairly positive about this change, and I feel like it's *already*
been approved by runtime-spec maintainers [1,2]:

+8 Alexander Morozov, Brandon Philips, Daniel Dao, Mrunal Patel, Qiang
   Huang, Tianon Gravi, Vincent Batts, Vishnu Kannan
-0
#1 Michael Crosby

But as a purely technical question, why does your LGTM get the
PullApprove button?  It's configured to look at
runtime-spec-maintainers [3], and you aren't one [4] (yet? ;).

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/x-Oh3PDz1Y8/q7t2IseVAwAJ
     Subject: [project-template adopted]: Merge 56abe122 (+13 -0 #5)
     Date: Wed, 20 Jul 2016 16:51:58 +0000
     Message-ID: <CAD2oYtPwMcF__WD32cV6dHgHt8=F6qFw+XFGw4iQK9LGi_QWsg@mail.gmail.com>
[2]: https://github.com/opencontainers/project-template/pull/15#issuecomment-234405104
     Subject: Add governance and releases docs
[3]: https://github.com/opencontainers/runtime-spec/blob/bb6925ea99f0e366a3f7d1c975f6577475ca25f0/.pullapprove.yml#L8
[4]: https://github.com/opencontainers/runtime-spec/blob/bb6925ea99f0e366a3f7d1c975f6577475ca25f0/MAINTAINERS

**Comment by vbatts** [comment]
LGTM

**Comment by cyphar** [comment]
I have no clue why I get a pull approve button. Maybe it's a sign? :wink:

**Comment by wking** [comment]
On Sat, Jul 23, 2016 at 05:41:35AM -0700, Vincent Batts wrote:
> LGTM

And @vbatts does not get a PullApprove button?  Maybe someone has
mixed up runc-maintainers and runtime-spec-maintainers when populating
the GitHub groups?

**Comment by cyphar** [comment]
I just checked. @vbatts is in the runtime-spec-maintainers group, and so am I (which I think is a mistake, I'll leave it now).

**Comment by wking** [comment]
On Sat, Jul 23, 2016 at 08:18:27AM -0700, Aleksa Sarai wrote:
> @vbatts is in the runtime-spec-maintainers group, and so am I (which
> I think is a mistake, I'll leave it now).

So that explains why you got the button, but we're still not sure why
@vbatts didn't.

**Comment by dqminh** [comment]
LGTM

**Pull request merged**
