### PR TITLE
Add annotations to the state json

### PR DESCRIPTION
**Pull request by duglin**
Closes: #480

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 01:25:37PM -0700, Doug Davis wrote:
>   * Add annotations to the state json

For previous work in this direction, see #188 (which was about adding
runtime-specified annotations to the state).  I think that was closed
prematurely after the config-author-specified annotations landed in
#331 [1].  Is there still interest in the runtime-specified
annotations use-case that lead to #188?  For example, runC apparently
injects a ‘bundle’ field into annotations to get it into the state
JSON [2].

When I suggested including config-author-specified content in the
state [3], @gao-feng pointed out that you could retrieve that
information via bundlePath [4].  If that route to the annotations is
not acceptable, should we just copy the whole config.json into the
state JSON [5]?  If not, how do we pick and choose what gets copied
over?

[1]: https://github.com/opencontainers/runtime-spec/issues/480#issuecomment-223405337
[2]: https://github.com/opencontainers/runc/pull/869/files#diff-e75bc7288fdc0ddc587b4152ecbd3933R105
[3]: https://github.com/opencontainers/runtime-spec/pull/188#issuecomment-146912525
[4]: https://github.com/opencontainers/runtime-spec/pull/188#issuecomment-147026995
[5]: https://github.com/opencontainers/runtime-spec/issues/480#issuecomment-223405337

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
While this looks fine, we need to be clear about what we copy from the configuration to the state as it is essentially redundant.

**Comment by crosbymichael** [comment]
@mrunalp yes,  Since annotations are more user defined "labels" for a container not part of the configuration that create the container and its settings it makes since for something like this to be added to the state allow it to be a queried

**Comment by mrunalp** [comment]
@crosbymichael They could also potentially be used to implement extensions that aren't yet in the spec.

**Comment by crosbymichael** [comment]
@mrunalp yep, its something for external tooling, the runtime will just passthough and take no actions on the values.

**Comment by mrunalp** [comment]
I am fine merging for now and we could maybe revisit if we see a need to move other values into the state. Thanks!

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
