### PR TITLE
config-linux: Add Memory cgroup's use_hierarchy

### PR DESCRIPTION
**Pull request by BooleanCat**
Addresses issue https://github.com/opencontainers/runtime-spec/issues/984

Signed-off-by: Tom Godkin <thgodkin@gmail.com>
Co-authored-by: Claudia Beresford <cberesford@pivotal.io>

### CODE REVIEW

**Comment by BooleanCat** [comment]
@crosbymichael Is the Signed-off-by check sensitive to its position in the commit message maybe? I do have it but it's before a Co-authored-by.

I swapped the order and force pushed but it doesn't seem to have poked travis to try again.

**Comment by crosbymichael** [comment]
Not sure. Maybe it wants both to be signed off

**Comment by georgethebeatle** [comment]
Pull approve won't accept the commit even though it has a Sign-off. Closing and going to reopen hoping this time it will not complain.

**Comment by crosbymichael** [comment]
LGTM

**Comment by BooleanCat** [comment]
Bump, seems like we another LGTM to get this merged. Once it's in we can work on getting runc to do something with this property.

**Comment by vbatts** [comment]
this doesn't just apply to cgroups v2? perhaps that ought to be clarified that it's for propagating to nested/child groups, regardless to using cgroups of v2.

**Comment by vbatts** [comment]
_house keeping:_ this is an OPTIONAL feature, so non-breaking forward compatible.

LGTM

**Pull request merged**
