### PR TITLE
seccomp: Add ppc and s390x to specs-go/config.go

### PR DESCRIPTION
**Pull request by michael-holzheu**
Proably needed to complete docker/docker#22922

Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by justincormack** [comment]
LGTM

**Comment by mrunalp** [comment]
Needs rebase. (We probably should follow up with github on this.)

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@mrunalp no rebase needed now that we fixed the branch issue

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
