### PR TITLE
Remove ffjson because of gccgo issues

### LINKED ISSUE #362: Specs don't build on gccgo
After #343 building with gccgo seems to fail:

```
22:23:58 + git clone https://github.com/opencontainers/runc.git /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:23:58 Cloning into '/tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc'...
22:24:00 + cd /tmp/tmp.Mst50n3vK1/src/github.com/opencontainers/runc
22:24:00 + git checkout -q 0c1c615ebd6a15545b6a82ead01d2745ea49b242
22:24:00 + make static BUILDTAGS=seccomp apparmor selinux
22:24:00 CGO_ENABLED=1 go build -tags "seccomp apparmor selinux cgo static_build" -ldflags "-w -extldflags -static -X main.gitCommit=0c1c615ebd6a15545b6a82ead01d2745ea49b242" -o runc .
22:24:00 go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
22:24:08 # github.com/pquerna/ffjson/fflib/v1
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s: Assembler messages:
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:6: Error: no such instruction: `text scanStringSSE(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:15: Error: no such instruction: `text ·haveSSE42(SB),NOSPLIT,$0'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:16: Error: too many memory references for `xor'
22:24:08 Godeps/_workspace/src/github.com/pquerna/ffjson/fflib/v1/reader_scan_amd64.s:21: Error: too many memory references for `mov'
22:24:09 Makefile:21: recipe for target 'static' failed
22:24:09 make: *** [static] Error 2
```

### PR DESCRIPTION
**Pull request by crosbymichael**
Fixes #362

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
51f8868 looks good to me.

This will also require dropping ffjson from #349 if this PR lands
first.

**Comment by JakeWarner** [comment]
LGTM

**Comment by vbatts** [comment]
so many lines.
@crosbymichael is there any other way you can still benefit from the unmarshal speed improvements?

**Comment by crosbymichael** [comment]
not that i know of at this point

**Comment by vbatts** [comment]
i wonder if having a build tag + go:generate would allow a way around incompatible things like gccgo?

**Comment by wking** [comment]
On Thu, Mar 31, 2016 at 11:52:21AM -0700, Michael Crosby wrote:
> not that i know of at this point

The cludgy approach would be “fork this repo and keep ffjson in the
fork” (this could maybe happen in a separate long-running branch of
this repo, but I'm not clear enough on Go vendoring to know).  Then
consumers could pick whichever implementation matched their preferred
performance / portability balance.  With the ffjson being
autogenerated, maintaining the fork shouldn't be too much work.

**Comment by vbatts** [comment]
@wking noup

**Comment by wking** [comment]
On Thu, Mar 31, 2016 at 12:00:56PM -0700, Vincent Batts wrote:
> i wonder if having a build tag + go:generate would allow a way
> around incompatible things like gccgo?

This also sounds promising to me, and would certainly be cleaner than
using two branches/repos if it works out.

**Comment by JakeWarner** [comment]
I'd wait to potentially re-integrate ffjson until the issue behind https://github.com/pquerna/ffjson/pull/172 is resolved as any golang1.6 builds aren't consistent due to the spec having anonymous structs. I see that @crosbymichael closed https://github.com/opencontainers/runtime-spec/pull/361 due to this pull request.

**Comment by crosbymichael** [comment]
ya, i think we can remove for now and work with upstream to fix some of the issues that we have

**Comment by vbatts** [comment]
sounds fine.

LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
