### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by vbatts**
Since 1.0.0:
4ebb31efe97cf3daedb1e331663395edfb56f284 Merge pull request #925 from wking/absolute-namespace-path-must
34170989dc28be797f7078f88df156a474d7fd11 Merge pull request #913 from rutsky/fix-link
a8125598b32a65ff55c83214d3c262383178e7fa Merge pull request #924 from wking/mailmap
f09dac8ed963f3a77561f45372de940f823ef351 Merge pull request #922 from jodh-intel/implementations-add-cc-runtime
325e66a6635c2bc78fafbfd994010c9ea4ead824 Merge pull request #921 from giuseppe/fix-typo
689521f Merge pull request #915 from wking/rlimits-unmapped-period
f5f1390 Merge pull request #910 from wking/monthly-meetings
ec96974 Merge pull request #902 from wking/pull-approve-v2
2a67f81 Merge pull request #900 from wking/oci-runtime-specification
3294695 Merge pull request #825 from Mashimiao/fix-blkio-spec
b747937 Merge pull request #901 from wking/config-title
49c255e Merge pull request #892 from q384566678/solaris-fix
c47d8e6 Merge pull request #907 from wking/container-process
63af112 Merge pull request #886 from q384566678/config-shchema-fix
0ee0850 Merge pull request #891 from q384566678/windows-fix
30bdf3b Merge pull request #889 from q384566678/intelRdt-add
6d696f5 Merge pull request #906 from wking/procfs-to-proc-link-label
1c9ab42 Merge pull request #905 from Mashimiao/procfs-proc
1df1fb3 Merge pull request #899 from 0x0916/update-schema
337efca Merge pull request #893 from opencontainers/bump-version

### CODE REVIEW

**Comment by wking** [comment]
Missing the [ChangeLog I'd worked up][1]?

[1]: http://ircbot.wl.linuxfoundation.org/eavesdrop/%23opencontainers/%23opencontainers.2017-09-06.log.html#t2017-09-06T21:37:29

**Comment by hqhq** [comment]
Yeah with changelogs would be better.

**Comment by hqhq** [comment]
@vbatts Can we resend the vote out with changelogs?

**Comment by wking** [comment]
I've bumped [my ChangeLog branch][1] to include f09dac8 (landing #922), since that's the current master tip.

[1]: https://github.com/wking/opencontainer-runtime-spec/tree/1.0.1-changelog

**Comment by wking** [comment]
I've bumped [my ChangeLog branch][1] to a970c47 to include 34170989 (landing #913), since that's the current master tip.

[1]: https://github.com/wking/opencontainer-runtime-spec/tree/1.0.1-changelog

**Comment by wking** [comment]
I've bumped [my ChangeLog branch][1] to fc77012 to include a5276ae (landing #929), since that's the current master tip.

[1]: https://github.com/wking/opencontainer-runtime-spec/tree/1.0.1-changelog

**Comment by vbatts** [comment]
good info. Maybe I can get to this today

**Comment by hqhq** [comment]
LGTM

**Comment by hqhq** [comment]
@opencontainers/runtime-spec-maintainers Vote's been passed in mailing list, can we get this merged?

**Comment by tianon** [comment]
LGTM

**Review by Loveisweird — APPROVED** [review]

**Pull request merged**
