### PR TITLE
schema: add cpu idle

### PR DESCRIPTION
**Pull request by giuseppe**
commit 9d363b36f6a7db184b0f7cc67b6f79204fb50107 added the feature but
didn't update the json schema file.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by vbatts — APPROVED** [review]
ah yeah. I wish there was a CI to block on missing schema coverage

**Review by flouthoc — APPROVED** [review]

**Comment by giuseppe** [comment]
@crosbymichael @cyphar @dqminh @hqhq @mrunalp @tianon PTAL

**Review by tianon — APPROVED** [review]
This doesn't need any changes for #1146, right?

**Comment by giuseppe** [comment]
> This doesn't need any changes for #1146, right?

I think we should be fine.  #1146 is just a fix for the Go library to make clear when the value was specified in the configuration.

In the example we have in `config.md`:

```json
            "cpu": {
                "shares": 1024,
                "quota": 1000000,
                "period": 500000,
                "realtimeRuntime": 950000,
                "realtimePeriod": 1000000,
                "cpus": "2-3",
                "idle": 1,
                "mems": "0-7"
            },
```

`idle` has just the int64 value and it follows the schema update proposed here

**Review by kolyshkin — APPROVED** [review]
LGTM

**Pull request merged**
