### PR TITLE
Fix "omitempty" typo

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <teabee89@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

for after the freeze

**Comment by tianon** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM
@crosbymichael like for a point release?

**Comment by crosbymichael** [comment]
@vbatts oh, i didn't know if we were still merging stuff or waiting until the release is done

**Comment by vbatts** [comment]
we can merge. It won't affect the tagged commit.

**Comment by vbatts** [comment]
not unless you want to _include_ this in the tagged commit. Then I would
need to update the PR for the version bump.

**Pull request merged**
