### PR TITLE
Bump version for 1.0.0-rc4

### PR DESCRIPTION
**Pull request by vbatts**
`git log --oneline --merges v1.0.0-rc3...7b10218 | awk '{ print $5 }' | wc -l`

#216
#664
#545
#665
#465
#660
#650
#655
#490
#654
#656
#653
#652
#645
#647
#649
#646
#607
#648
#427
#612
#643
#637
#639
#636
#640
#638
#642

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

(pending runtime-spec ML vote results)

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
