### PR TITLE
Release v1.0.2

### LINKED ISSUE #1010: Tag a new release
Hi there,

Do you think it would be possible to tag a new release according to semver? Some go module based dependencies have to rewrite their go.mod to get the latest features in. :innocent:  Thanks in advance! :)

### PR DESCRIPTION
**Pull request by vbatts**
Fixes #1010 

VOTE: https://groups.google.com/a/opencontainers.org/d/msg/dev/lYFhr-kmSAQ/9QmAI6yVDAAJ

PRs since v1.0.1:
e09c7c4 Merge pull request #1008 from RenaudWasTaken/hooks
020fda7 Merge pull request #1024 from giuseppe/add-personality-schema
bab266e Merge pull request #898 from 0x0916/fix-weight-type
2d3f265 Merge pull request #903 from wking/state-version-source
903de9f Merge pull request #916 from wking/unknown-properties-one-must
68f17f5 Merge pull request #1012 from justincormack/personality
8b180f3 Merge pull request #985 from masters-of-cats/master
cd13d2d Merge pull request #941 from cyphar/config-umask-option
19e92ca Merge pull request #1019 from pjbgf/add-act-log
52e2591 Merge pull request #1018 from giuseppe/seccomp-flags
4f2ab15 Merge pull request #1017 from giuseppe/fix-crun-repository
c9a5f61 Merge pull request #1016 from estesp/update-meetings
a950415 Merge pull request #1013 from odinuge/hugetlb-pattern-fix
7a49e34 Merge pull request #1011 from odinuge/hugetlb-pattern
8ffda14 Merge pull request #1009 from KentaTada/Fix-sample-ociVersion
5b71a03 Merge pull request #1007 from KentaTada/Fix-Namespaces-to-use-LinuxNamespaceType
a1b50f6 Merge pull request #1006 from lifubang/pidnamespace
ad53dcd Merge pull request #999 from jterry75/layerfolder_order
197975d Merge pull request #1001 from vsoch/update/CoC-link
29686db Merge pull request #998 from jhowardmsft/jjh/commandline
1722abf Merge pull request #992 from xiaochenshen/rdt-mba-software-controller
31e0d16 Merge pull request #994 from q384566678/vm-parameters-fix
038448f Merge pull request #993 from HaraldNordgren/go_versions
5806c35 Merge pull request #981 from kinvolk/alban/source-mount
5684b8a Merge pull request #932 from xiaochenshen/rdt-mba
cc07cb9 Merge pull request #988 from linericyang/master
eba862d Merge pull request #989 from dineshgovindasamy/windowsnamespace
d810dbc Merge pull request #976 from cwilhit/master
34fd552 Merge pull request #977 from wking/2018-07-04-meeting-bump
7c4c8f6 Merge pull request #969 from jodh-intel/add-kata-containers-to-implementations
695b816 Merge pull request #965 from wking/console-man-page
16d4c82 Merge pull request #970 from opencontainers/add-gvisor
c102f09 Merge pull request #968 from wking/bump-go
a1998ec Merge pull request #953 from kinvolk/alban/hook-paths
b4a682c Merge pull request #952 from ntrrg/patch-1
3234dc8 Merge pull request #959 from kinvolk/alban/957-device-owners
c09d7f4 Merge pull request #951 from wking/json-from-rfc-8259
4ad8e74 Merge pull request #943 from wking/2018-jan-meeting
d362ed3 Merge pull request #949 from sameo/vm-section
6be516e Merge pull request #956 from kinvolk/alban/uid-mapping
fa4b36a Merge pull request #942 from paravmellanox/master
7a8c2c8 Merge pull request #947 from q384566678/fix-makefile-test
520c634 Merge pull request #945 from wking/json-schema-minimal-ids
b2d941e Merge pull request #940 from q384566678/defaultAction-fix
75c847a Merge pull request #933 from q384566678/hook-link
a5b8598 Merge pull request #936 from wking/root-dedent

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

(Pending the vote result, of course)

**Comment by vbatts** [comment]
Current VOTE failed. Will post another subsequent vote later

**Comment by h-vetinari** [comment]
> @vbatts (in the mail thread linked in the OP):
Hey all,
We failed to meet the 2/3 quorum (https://github.com/opencontainers/runtime-spec/blob/master/GOVERNANCE.md#quorum) needed for this release.
We'll go back to the drawing board, and it will allow for further refinement before posting the vote again. In the meantime, due to the length of time since last release, perhaps we should evaluate active maintainers so progress isn't blocked.

From what I can see on the mail thread there was only one small nits, several LGTMs, and no objections. The only reason the vote failed is due to the 2/3rd requirement for vote participation. In light of this I think a re-evaluation of (active) maintainership is the next obvious step, rather than "going back to the drawing board" regarding the content of the release.

**Comment by vbatts** [comment]
That is more to the point I intended. Some of inactive maintainers should step down

-------- Original Message --------

**Comment by h-vetinari** [comment]
With no disrespect: it's kind of hard to get someone who's (apparently) not responding anymore to step down.

Maybe there should be a sort of "roll call" of the maintainers on the mailing list, and those who do not respond within a specific timeframe (e.g. 2 weeks) are set to "inactivate". Once they return they could of course reclaim their spot - it's not about kicking anyone out, but about safeguarding an environment where progress can be made (PRs merged; releases tagged; etc.). All such supplemental information should of course be part of the initial "roll call" mail.

**Comment by vbatts** [comment]
Agreed. We discussed this in the weekly call, and I'm pursuing the topic
with inactive maintainers. I think we can reduce to 5 maintainers.
If inactive folks don't respond, then I will escalate to the TOB to
reconcile.

**Pull request closed without merging**
