### PR TITLE
Add Giuseppe Scrivano as a runtime spec maintainer

### PR DESCRIPTION
**Pull request by mrunalp**
@giuseppe ptal.

@opencontainers/runtime-spec-maintainers ptal.

**Needs at least two-thirds to pass (5 LGTMs).**
- [x] Michael Crosby <michael@docker.com> (@crosbymichael)
- [x] Mrunal Patel <mpatel@redhat.com> (@mrunalp)
- [x] Vincent Batts <vbatts@redhat.com> (@vbatts)
- [ ] Daniel, Dao Quang Minh <dqminh89@gmail.com> (@dqminh)
- [x] Tianon Gravi <admwiggin@gmail.com> (@tianon)
- [x] Qiang Huang <h.huangqiang@huawei.com> (@hqhq)
- [x] Aleksa Sarai <asarai@suse.de> (@cyphar)

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
@vbatts looks like your e-mail needs an update as well (it's almost mailing-list day!)

**Comment by mrunalp** [comment]
@thaJeztah yeah I noticed that while making this PR but we can handle those as separate PRs :)

**Comment by AkihiroSuda** [comment]
ping @opencontainers/runtime-spec-maintainers

**Comment by hqhq** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/opencontainers/runtime-spec/pull-request/1048/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=opencontainers/runtime-spec)

**Comment by caniszczyk** [comment]
friendly ping @opencontainers/runtime-spec-maintainers

**Comment by cyphar** [comment]
LGTM, I forgot about this. This cannot be merged yet -- I'll update the PR description to include the current vote.

/cc @opencontainers/runtime-spec-maintainers

**Comment by vbatts** [comment]
yay! 
LGTM
(and yes, my email needs to be updated)

**Comment by vbatts** [comment]
to get movement on this, @giuseppe might you provide a bit more of context on contributions and reasoning behind the recommendation here? activity, contributions, etc.
(not everyone has worked with you)

**Comment by giuseppe** [comment]
> to get movement on this, @giuseppe might you provide a bit more of context on contributions and reasoning behind the recommendation here? activity, contributions, etc.
> (not everyone has worked with you)

I am the main author of [crun](https://github.com/containers/crun).  I've got the most experience with the runtime specs working on it.

I've also contributed some other fixes for the runtime-specs: https://github.com/opencontainers/runtime-spec/pulls?q=is%3Apr+author%3Agiuseppe, in particular I've worked on adding support for cgroup v2: https://github.com/opencontainers/runtime-spec/pull/1040

**Review by crosbymichael — APPROVED** [review]
LGTM

**Comment by tianon** [comment]
Thanks for adding some additional detail (and for your work here)!

LGTM

**Comment by cyphar** [comment]
Passes with 6 LGTMs (of 5 required), welcome to the crew @giuseppe!

**Comment by giuseppe** [comment]
thanks everyone!  :smile:

**Pull request closed without merging**
