### PR TITLE
Make pid option on platforms other than linux

### PR DESCRIPTION
**Pull request by crosbymichael**
Closes #895

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
Do you want to pick [these][1] up too?

[1]: https://github.com/opencontainers/runtime-spec/pull/895#issuecomment-314916355

**Comment by crosbymichael** [comment]
no, i'm not changing it to a pointer to an int

**Comment by crosbymichael** [comment]
I removed it in the schema code

**Comment by wking** [comment]
> no, i'm not changing it to a pointer to an int

Then are you at least setting `omitempty`?  Also, how is this different from [`timeout`, where you asked for a pointer][1]?

[1]: https://github.com/opencontainers/runtime-spec/pull/764#discussion_r111607155

**Comment by crosbymichael** [comment]
@wking lets not discuss pointers vs non-pointers here.  we have went round in circles before and i'm not going to start again

**Comment by crosbymichael** [comment]
@mrunalp @vbatts PTAL

**Comment by vbatts** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
