### PR TITLE
README: tweak title

### PR DESCRIPTION
**Pull request by jonboulle**
To be consistent with opencontainers/image-spec.

### CODE REVIEW

**Comment by vbatts** [comment]
DCO, y'all

**Comment by cyphar** [comment]
Please include a Signed-off-by line in your commit.

**Comment by jonboulle** [comment]
OMG

**Comment by vbatts** [comment]
Otherwise LGTM

**Comment by jonboulle** [comment]
So silly

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
You lgtm Vincent.

**Comment by vbatts** [comment]
yer face

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
