### PR TITLE
config-linux: add SHOULD to linux.namespaces.type

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

Carrying over a rebased #931

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

(Travis failure is the same one we're seeing on `master`)

**Comment by giuseppe** [comment]
> (Travis failure is the same one we're seeing on `master`)

it is fixed with #1024

**Comment by h-vetinari** [comment]
@vbatts can you rebase this?

**Comment by vbatts** [comment]
rebased PTAL

**Comment by tianon** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
