### PR TITLE
schema/README: Fix links to (config|state)-schema.json

### PR DESCRIPTION
**Pull request by jcfr**
Fix regression respectively introduced in 59ede1a and 59ede1a

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @wking

**Comment by wking** [comment]
Duplicates #498?

And, “I'm sorry, I'm sorry!” ;).

**Comment by wking** [comment]
Heh, even the same missing Signed-off-by as #498 [1] ;).

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/138200052#L226

**Comment by jcfr** [comment]
Ooops. Thanks for the review. 

Closing. Superseded by #501

**Pull request closed without merging**
