### PR TITLE
schema/README: Fix links to (config|state)-schema.json

### PR DESCRIPTION
**Pull request by jcfr**
Fix regression respectively introduced in 59ede1a and 59ede1a

Signed-off-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

### CODE REVIEW

**Comment by jcfr** [comment]
xref #498

**Comment by jcfr** [comment]
Cc: @wking

**Comment by jcfr** [comment]
Et voila :smile:

**Comment by wking** [comment]
2de20197 looks good to me (and you could have force pushed to your
patch-1 branch to update #500).

I don't know whether #498 should be held open for some time to give
@leecalcotes a chance to sign his commit, but he's been quiet so far
and this is a small change, so I doubt he'd mind if this PR landed and
scooped him ;).

**Comment by jcfr** [comment]
> force pushed to your patch-1 branch

Indeed, will do if such situation occurs again

> held open for some time

Makes sense.

Cc: @leecalcote

**Comment by leecalcote** [comment]
I'm happy to update my commit. Just tell me what needs to be done. A git commit --amend?

**Comment by wking** [comment]
On Thu, Jun 16, 2016 at 03:20:40PM -0700, Lee Calcote wrote:
> I'm happy to update my commit. Just tell me what needs to be done. A
> git commit --amend?

Something like:

  $ git checkout patch-1
  $ git commit --amend --signoff --no-edit
  $ git push --force leecalcote patch-1

will update #498.  But you'll want to make sure you're ok with what
you're signing first [1] ;).

[1]: https://github.com/opencontainers/runtime-spec/tree/v1.0.0-rc1#sign-your-work

**Comment by leecalcote** [comment]
Thanks @wking. I think #498 is good to go now.

**Comment by jcfr** [comment]
Nice. Closing this PR .. it is superseded by #498

**Pull request closed without merging**
