### PR TITLE
MAINTAINERS: remove philips

### PR DESCRIPTION
**Pull request by philips**

### CODE REVIEW

**Comment by tianon** [comment]
Thanks for your contributions over the years!!

LGTM

@vbatts @caniszczyk do you think we need to enforce the DCO on such a trivial commit, or can we go ahead without that for this?

**Comment by tianon** [comment]
(Also, do we really need three separate systems checking DCO?? :sweat_smile:)

**Comment by vbatts** [comment]
I was wondering about that. I might can force push over it.

-------- Original Message --------

**Comment by vbatts** [comment]
We.. Have three checks for DCO?

-------- Original Message --------

**Comment by vbatts** [comment]
fixed

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
pullapprove is confused. Fixed in https://github.com/opencontainers/runtime-spec/pull/1029

**Comment by vbatts** [comment]
Big thanks to all your effort and history on this spec, @philips

**Comment by vbatts** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

❤️

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
