### PR TITLE
.mailmap: Add entries for inconsistent users

### PR DESCRIPTION
**Pull request by wking**
Similar to opencontainers/runtime-tools#115.

Where the same user had multiple entries, I mostly went with whichever entry had the most-recent non-merge commits.  Before this commit:

    $ git shortlog -se
     ...
       6  Aleksa Sarai <asarai@suse.de>
       2  Aleksa Sarai <cyphar@cyphar.com>
       6  Alexander Morozov <lk4d4@docker.com>
      12  Alexander Morozov <lk4d4math@gmail.com>
       1  Amit Saha <amitsaha.in@gmail.com>
       1  Amit Saha <amitsaha@users.noreply.github.com>
       6  Antonio Murdaca <runcom@linux.com>
       2  Antonio Murdaca <runcom@redhat.com>
       8  Brandon Philips <brandon.philips@coreos.com>
       6  Brandon Philips <brandon@ifup.co>
      18  Brandon Philips <brandon@ifup.org>
     ...
       1  Daniel Dao <dqminh89@gmail.com>
      19  Daniel, Dao Quang Minh <dqminh89@gmail.com>
     ...
      14  Doug Davis <dug@us.ibm.com>
       1  Doug Davis <duglin@users.noreply.github.com>
     ...
       1  John Howard <John.Howard@microsoft.com>
       9  John Howard <jhoward@microsoft.com>
     ...
       1  Liang Chenye <liangchenye@huawei.com>
     ...
       1  Mrunal Patel <mrunal@Mrunals-iMac.local>
       1  Mrunal Patel <mrunal@dhcp-16-185.sjc.redhat.com>
     174  Mrunal Patel <mrunal@me.com>
      31  Mrunal Patel <mrunalp@gmail.com>
     ...
     171  Vincent Batts <vbatts@hashbangbash.com>
       5  Vincent Batts <vbatts@redhat.com>
     ...
       5  Vish Kannan <vishh@users.noreply.github.com>
       1  Vishnu Kannan <vishnuk@google.com>
       5  Vishnu kannan <vishnuk@google.com>
     ...
       1  Zefan Li <lizefan@huawei.com>
       1  Zefan Li <lizf1984@hotmail.com>
     ...
       1  liangchenye <liangchenye@huawei.com>
     ...
       5  v1.0.0.batts <vbatts@hashbangbash.com>
     ...
       1  梁辰晔 (Liang Chenye) <liangchenye@huawei.com>

With Liang, I went with the version that also included the logograms, because logograms are cool and it [matches his GitHub name][1] ;).

The order is alphabetical according to Emacs' sort-lines.

Details on the format in `git-shortlog(1)`.

[1]: https://github.com/liangchenye

### CODE REVIEW

**Comment by caniszczyk** [comment]
Thanks @wking, this helps as I draft some of the thank you notes towards the v1.0 release

**Comment by caniszczyk** [comment]
cc: @opencontainers/runtime-spec-maintainers

**Comment by tianon** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
