### PR TITLE
Support for network namespace in windows

### PR DESCRIPTION
**Pull request by dineshgovindasamy**
Signed-off-by: Dinesh Govindasamy <dingov@microsoft.com>
Co-Authored-By: msabansal <sabansal@microsoft.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
```
git-validation -q -run DCO,short-subject,dangling-whitespace
 9b47594 - FAIL - has whitespace errors. See `git show --check 9b47594383442579c974ef26d9505bdb7a51dcde`.
1 commits to fix
make: *** [.gitvalidation] Error 1
```

**Comment by dineshgovindasamy** [comment]
@crosbymichael I fixed the whitespaces but the Travis CI is still referring to the old commit and not the new Commit. Is there a way to rerun the CI with latest commit.

**Comment by dineshgovindasamy** [comment]
@crosbymichael Thanks it was the DCO issue. I fixed and now it succeeded.

**Comment by dineshgovindasamy** [comment]
@crosbymichael Could you please approve this PR?

cc @jhowardmsft

**Comment by crosbymichael** [comment]
LGTM

**Comment by dineshgovindasamy** [comment]
@tianon Could you please approve this PR? Please let me know if you have any questions.

Cc @jhowardmsft

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
