### PR TITLE
Remove code-of-conduct.md and version.md when clean

### PR DESCRIPTION
**Pull request by hqhq**
So we can use latest files after make clean.

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
c57a0238 looks good to me.

**Comment by crosbymichael** [comment]
Where do these files come from?

**Comment by wking** [comment]
On Fri, Aug 26, 2016 at 09:53:18AM -0700, Michael Crosby wrote:
> Where do these files come from?

They're built for the docs [1,2].

[1]: https://github.com/opencontainers/runtime-spec/blob/069e8e1c16765e792ddefb32a6ad52e0c70b05ae/Makefile#L58-L62
[2]: https://github.com/opencontainers/runtime-spec/blob/069e8e1c16765e792ddefb32a6ad52e0c70b05ae/Makefile#L58-L62

**Comment by crosbymichael** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
