### PR TITLE
Bump v1.0rc1

### PR DESCRIPTION
**Pull request by vbatts**
where ef1aa37acb7052e5b44948550fceb98ed94481a9 would be tagged `v1.0.0-rc1`

### CODE REVIEW

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 12:17:15PM -0700, Vincent Batts wrote:
>   * version: v1.0.0-rc1

The series through 41bfb585 looks fine to me, although I went with
“rc.1” in the ChangeLog to match SemVer's own versioning [1].  §9
talks about “dot separated identifiers” in the pre-release version.
But it probably only matters for sorting (e.g. rc10 probably sorts
before rc9, but rc.10 probably sorts after rc.9).

[1]: http://semver.org/v2.0.0.html

**Comment by vbatts** [comment]
@wking the link is a 404.

I'm not really sure that I've run into `-rc.N` much if ever. While I don't entirely care, it is very common to see `-rcN`

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 12:29:29PM -0700, Vincent Batts wrote:
> @wking the link is a 404.

Sorry, should have been: http://semver.org/spec/v2.0.0.html

> I'm not really sure that I've run into `-rc.N` much if ever. While I
> don't entirely care, it is very common to see `-rcN`

We're unlikely to hit rc.10 ;).  I think we should follow the SemVer
example, but yeah, it doesn't matter much.  Whichever way we go, the
ChangeLog, subsequent Go, and tag should be consistent.

**Comment by crosbymichael** [comment]
rc1 over rc.1 is much better

**Comment by crosbymichael** [comment]
LGTM

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 12:58:28PM -0700, Michael Crosby wrote:
> rc1 over rc.1 is much better

I don't see *much* difference, and certainly nothing superior about
the short form, but feel free to reroll my ChangeLog commit to adjust
‘rc.1’ → ‘rc1’.

**Comment by crosbymichael** [comment]
It already is adjusted

**Comment by tianon** [comment]
LGTM

IIRC, rc.N is primarily a python thing, but IMO rcN looks better and is much more common

**Comment by mrunalp** [comment]
LGTM

**Comment by crosbymichael** [comment]
@vbatts let me know if you get a chance to push the tag or i can do it

**Comment by crosbymichael** [comment]
06479209bdc0d4135911688c18157bd39bd99c22 should be the new commit to tag correct?

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 03:03:17PM -0700, Michael Crosby wrote:
> 06479209bdc0d4135911688c18157bd39bd99c22 should be the new commit to tag correct?

Yup.

**Comment by crosbymichael** [comment]
ok, pushed the tag

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 03:23:14PM -0700, Michael Crosby wrote:
> ok, pushed the tag

Not signed?

**Pull request merged**
