### PR TITLE
Hide output dir from git

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by vbatts** [comment]
I guess so... I've gotten to where I don't add much to a repo's `.gitignore`, and just have a person `git config --global --add core.excludesfile ~/.cvsignore`.

**Comment by wking** [comment]
e284801c looks good to me.

@vbatts, do you have an output-ignore rule in your global config?  It
seems like it would be specific to this repo.

**Comment by hqhq** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
