### PR TITLE
RELEASE: document how to do the release

### PR DESCRIPTION
**Pull request by vbatts**
It's been a couple of years and I have no idea what I am doing.
Some of this could be automated, but for now I've included some of the
shell that gets close to the process.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

image

### CODE REVIEW

**Comment by tianon** [comment]
LGTM

I appreciate having the full nutty process documented. :heart: 

In the future, I'd love to open a discussion about deprecating the changelog file because, well, Git.

**Comment by vbatts** [comment]
@tianon yes. I'm all for switching those manual things, so it's just a script for:
> here's the variables needed...
> here's the email to copy-paste ...

**Comment by vbatts** [comment]
@opencontainers/runtime-spec-maintainers PTAL

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
