### PR TITLE
[Config Linux] Clarify: App --> Container

### PR DESCRIPTION
**Pull request by RobDolinMS**
Replaces #577

Signed-off-by: Rob Dolin (MSFT) <robdolin@microsoft.com>

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

**Comment by wking** [comment]
I have no idea why git-validation is looking at these ancient commits
[1].

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/193139559#L285

**Comment by mrunalp** [comment]
@vbatts PTAL

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
