### PR TITLE
Bump version for v0.5.0 release

### PR DESCRIPTION
**Pull request by vbatts**

### CODE REVIEW

**Comment by wking** [comment]
I have a ChangeLog commit (through 6734c7a, #370) here [1] if you want
to put that in before the 0.5.0 commit.

[1]: https://github.com/wking/opencontainer-runtime-spec/tree/0.5.0

**Comment by vbatts** [comment]
pulled in your ff6e729d62c8e9062ac98fcc8cdb4a5cefa52707 commit

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@crosbymichael @vishh PTAL

**Comment by vishh** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@vbatts i'll let you merge and tag

**Comment by wking** [comment]
Looks like this missed bumping the example to 0.6.0-dev [1,2].  Maybe
add a note to project.md?

[1]: https://github.com/opencontainers/runtime-spec/blob/v0.5.0/config.md#configuration-schema-example
[2]: https://github.com/opencontainers/runtime-spec/pull/370#discussion_r58783380

**Comment by vbatts** [comment]
@wking not a strict need.

**Comment by wking** [comment]
On Tue, Apr 12, 2016 at 12:22:46PM -0700, Vincent Batts wrote:
> @wking not a strict need.

Then I'd rather use a real version number there instead of the current
-dev.  And we'd need to remember to bump when any 0.6.0-specific
content landed in the example.

**Pull request merged**
