### PR TITLE
MAINTAINERS: update vbatts email

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
hrm, @crosbymichael michael@docker.com doesn't work anymore either

**Review by crosbymichael — APPROVED** [review]
LGTM

**Comment by crosbymichael** [comment]
ya, mine needs to be updated as well

**Review by tianon — APPROVED** [review]
LGTM

**Pull request merged**
