### PR TITLE
implementations: add railcar

### PR DESCRIPTION
**Pull request by vbatts**
Obsoletes #883
Obsoletes #995

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by josegonzalez** [comment]
Thanks for picking this up, I totally forgot to sign this...

**Comment by tianon** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
(heh, can't LGTM my own PR ;-)

**Comment by h-vetinari** [comment]
Trivial change that's only missing an LGTM because pullapprove doesn't count the PR owner;
@caniszczyk @crosbymichael @dqminh @hqhq @mrunalp

**Comment by cyphar** [comment]
It should be noted that `railcar` has since been archived as a project.

**Comment by h-vetinari** [comment]
So I'm guessing this PR can just be closed, then. Even easier. :)

**Comment by tianon** [comment]
Good call :disappointed:

**Pull request closed without merging**
