### PR TITLE
updating link to code of conduct in org repository

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

This will update the code-of-conduct.md document to point to the one (that will be linked) from the updated org repo. The current points to the "tob" repository.

### CODE REVIEW

**Comment by vbatts** [comment]
LGTM

**Comment by vsoch** [comment]
Code of conduct link is updated to be outside of .github (and in all caps) to reflect discussion in OCI call.

**Comment by vbatts** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by vsoch** [comment]
Thank you! :D

**Comment by vsoch** [comment]
*dancing avocado*

**Pull request merged**
