### PR TITLE
schema: add missing definition for personality

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/opencontainers/runtime-spec/issues/1023

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@justincormack PTAL

**Comment by giuseppe** [comment]
I needed to add a couple of extra fixes to make the CI happy

**Comment by justincormack** [comment]
Thanks for doing this, LGTM.

**Comment by tianon** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
