### PR TITLE
README: Fix broken link for charter

### PR DESCRIPTION
**Pull request by cfelder**

### CODE REVIEW

**Review by tianon — APPROVED** [review]
Nice catch, LGTM

**Comment by tianon** [comment]
(Although your commit needs to be amended with a DCO :sweat_smile:)

**Comment by cfelder** [comment]
Added missing signed off sorry.

**Review by tianon — APPROVED** [review]
re-LGTM :+1:

**Comment by tianon** [comment]
cc @opencontainers/runtime-spec-maintainers (easy merge, only need one more maintainer :wink:)

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
