### PR TITLE
MAINTAINERS: add Toru Komatsu (utam0k)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
@utam0k is a maintainer of [youki ](https://github.com/containers/youki) and has been actively contributing to the spec:
https://github.com/search?q=repo%3Aopencontainers%2Fruntime-spec+type%3Aissue+involves%3Autam0k&type=pullrequests

<hr>

Maintainer votes (at least **8** of 11 maintainers needed for this resolution to pass):
- [ ] @crosbymichael
- [x] @mrunalp
- [x] @vbatts
- [x] @dqminh
- [ ] @tianon
- [x] @hqhq
- [x] @cyphar
- [x] @giuseppe
- [x] @AkihiroSuda
- [x] @kolyshkin
- [x] @thaJeztah

### CODE REVIEW

**Comment by utam0k** [comment]
Thanks a lot 🙏

**Comment by AkihiroSuda** [comment]
ping @opencontainers/runtime-spec-maintainers

**Comment by caniszczyk** [comment]
@AkihiroSuda you can always send a reminder to the dev@oci mailing list too

**Comment by estesp** [comment]
Not a maintainer, but definitely in favor!

**Review by cyphar — APPROVED** [review]
LGTM! He'd be an amazing addition as a maintainer to our project.

**Review by vbatts — APPROVED** [review]
😺

**Comment by utam0k** [comment]
👋Hi @crosbymichael @mrunalp @dqminh @tianon @hqhq@kolyshkin, This PR still needs three more approvals. There are several regular PRs already out there that I'd like to review. Currently, I'm unable to do so. Would you be able to help with the review? 🙏

**Comment by hqhq** [comment]
LGTM

**Review by kolyshkin — APPROVED** [review]
LGTM

**Comment by utam0k** [comment]
Hello @crosbymichael @mrunalp @dqminh @tianon
This humble PR is sitting at 7/8 approvals. It's just one review away from reaching it is being merged. It feels like waiting for the last piece of pizza to be delivered 🍕 Can someone help deliver this 'slice' of approval? 😄🙏

**Review by fuweid — COMMENTED** [review]
LGTM!

**Comment by mrunalp** [comment]
LGTM

**Comment by utam0k** [comment]
@fuweid @mrunalp @dqminh 
Thanks for your reaction :pray:

**Comment by AkihiroSuda** [comment]
9 approvers (including myself), so I'm merging this.
Welcome @utam0k

**Comment by AkihiroSuda** [comment]
@caniszczyk Could you invite @utam0k ?

**Comment by caniszczyk** [comment]
done welcome!

**Comment by AkihiroSuda** [comment]
Thank you!

**Comment by utam0k** [comment]
I am happy to participate! Thanks.

**Pull request merged**
