### PR TITLE
schema/Makefile: fix test

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
Bump :).  This is [blocking][1] #942.

[1]: https://github.com/opencontainers/runtime-spec/pull/942#issuecomment-367146252

**Comment by wking** [comment]
@q384566678, can you rebase onto master to pick up #945 and avoid [the current Travis error][1]?

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/331708753#L601

**Comment by q384566678** [comment]
updated, @crosbymichael @hqhq PTAL

**Comment by hqhq** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
