### PR TITLE
schema: add username for user field

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by cyphar** [comment]
As far as I can tell, this field is not defined in the spec?

**Comment by wking** [comment]
On Tue, Feb 28, 2017 at 05:19:25AM -0800, Aleksa Sarai wrote:
> As far as I can tell, this field is not defined in the spec?

It's defined here [1].

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.0-rc4/config.md#windows-user

**Comment by wking** [comment]
Bump?

**Comment by Mashimiao** [comment]
ping @opencontainers/runtime-spec-maintainers

**Comment by hqhq** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Pull request merged**
