### PR TITLE
MAINTAINERS: move vbatts to EMERITUS

### PR DESCRIPTION
**Pull request by vbatts**
Happy to still be brought into conversations, but do not want to slow progress of the active maintainers.

🐐🧁🧡

Also, building out the EMERITUS from the past folks that have already retired out of being maintainers.

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM ❤️

**Review by AkihiroSuda — APPROVED** [review]
Thank you @vbatts

**Review by hqhq — APPROVED** [review]
LGTM

**Review by tianon — APPROVED** [review]
❤️

**Comment by utam0k** [comment]
Thanks, @vbatts

**Review by utam0k — APPROVED** [review]

**Pull request merged**
