### PR TITLE
MAINTAINERS: Add @cyphar as maintainer

### PR DESCRIPTION
**Pull request by giuseppe**
I propose Aleksa Sarai (@cyphar) to be added to the runtime-spec maintainers.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@crosbymichael @mrunalp @vbatts @dqminh @tianon @hqhq PTAL

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by giuseppe** [comment]
there are two LGTM, can it be merged?

**Comment by cyphar** [comment]
For maintainer additions, you need a 2/3rd vote. Namely, we need 4 of the following folks to LGTM it:

- [ ] @crosbymichael
- [x] @mrunalp
- [ ] @vbatts
- [ ] @dqminh
- [ ] @tianon
- [x] @hqhq

**Comment by dqminh** [comment]
LGTM.

This is great !

**Comment by vbatts** [comment]
LGTM

**Comment by vbatts** [comment]
with a 4/6 vote

**Pull request merged**
