### PR TITLE
Use filesystem instead of file system

### PR DESCRIPTION
**Pull request by coolljt0725**
Change `file system` to `filesystem`
Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Aug 11, 2016 at 07:42:35PM -0700, Lei Jitang wrote:
> Change `file system` to `filesystem`

+1 on the change:

  $ git remote -v
  origin  git://git.kernel.org/pub/scm/docs/man-pages/man-pages.git (fetch)
  origin  git://git.kernel.org/pub/scm/docs/man-pages/man-pages.git (push)
  $ git describe
  man-pages-4.06-441-gaa30354
  $ git grep -i 'file.system' | wc -l
  36
  $ git grep -i 'filesystem' | wc -l
  879

But you're missing some instances from runtime-spec:

  $ git remote -v | grep origin
  origin  git://github.com/opencontainers/runtime-spec.git (fetch)
  origin  git://github.com/opencontainers/runtime-spec.git (push)
  $ git describe origin/pr/529
  v1.0.0-rc1-48-g6c3d2e6
  $ git grep -i 'file.system' origin/pr/529 | wc -l
  2
  $ git grep -i 'file.system' origin/pr/529
  origin/pr/529:config-linux.md:The Linux container specification uses various kernel features like namespaces, cgroups, capabilities, LSM, and file system jails to fulfill the spec.
  origin/pr/529:config-linux.md:## Default File Systems

**Comment by coolljt0725** [comment]
@wking  thanks, updated

**Comment by hqhq** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
