### PR TITLE
schema/README: Fix links to (config|state)-schema.json

### PR DESCRIPTION
**Pull request by leecalcote**
Fix regression respectively introduced in 59ede1a and 59ede1a

The config-schema.json and state-schema.json references were missing "-schema".

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 04:07:49PM -0700, Lee Calcote wrote:
> The config-schema.json and state-schema.json references were missing
> "-schema".

Oops, busted reroll in #481 :/.  644b888e is missing a Signed-off-by
[1,2], but other than that it looks good to me.

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/137379064#L226
[2]: https://github.com/opencontainers/runtime-spec/tree/v1.0.0-rc1#sign-your-work

**Comment by jcfr** [comment]
@leecalcote  

Nitpicks: May be you could amend and update the title/content to provide more context ? 

```
schema/README: Fix links to (config|state)-schema.json

Fix regression respectively introduced in 59ede1a and 59ede1a
```

**Comment by wking** [comment]
On Fri, Jun 17, 2016 at 10:31:58AM -0700, Jean-Christophe Fillion-Robin wrote:
> schema/README: Fix links to (config|state)-schema.json

Pushing this as a commit-message summary would be nice too, but that's
not a big deal.  And e319b858 looks good to me otherwise.

**Comment by leecalcote** [comment]
I just did a `git commit --amend` and `git push --force` on this patch with a revised message subject and summary.

**Comment by jcfr** [comment]
:8ball:

**Comment by vbatts** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
