### PR TITLE
[Runtime] Add anchor tags for headings and bullets

### PR DESCRIPTION
**Pull request by RobDolinMS**
Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Is that syntax defined by the markdown spec? Because I would expect that it would result in you having lots of trailing `<a>` tags.

**Comment by wking** [comment]
On Sat, Nov 12, 2016 at 06:03:32PM -0800, Aleksa Sarai wrote:
> Is that syntax defined by the markdown spec?

From the spec [1]:

  For any markup that is not covered by Markdown’s syntax, you simply
  use HTML itself…
  …
  Span-level HTML tags — e.g. <span>, <cite>, or <del> — can be used
  anywhere in a Markdown paragraph, list item, or header. If you want,
  you can even use HTML tags instead of Markdown formatting; e.g. if
  you’d prefer to use HTML <a> or  tags instead of Markdown’s
  link or image syntax, go right ahead.

So what @RobDolinMS has with e6fd589b is legal, although I'd prefer
moving to a markup language with better support for long-form docs
(#615).

[1]: http://daringfireball.net/projects/markdown/syntax#html

**Comment by vbatts** [comment]
needs a rebase

**Comment by mrunalp** [comment]
Needs rebase.

**Comment by crosbymichael** [comment]
@RobDolinMS when you have time please rebase your PRs and make sure your sign off is correct.  Feel free to reopen when they have been updated.

**Pull request closed without merging**
