### PR TITLE
config-schema: Optimize code

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by q384566678** [comment]
@dqminh @tianon @crosbymichael PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by wking** [comment]
I see @hqhq added this to the 1.1.0 milestone back on 2017-07-10 [1]
(and that's now the “1.Y.0” milestone [2]).  However, this PR looks
like a pure refactoring, with no impact on any possible consumers, so
it could land in a patch release (vs. a 1.1.0 minor release).  Can we
move it to the v1.0.Z milestone [3] (which @crosbymichael may have
created yesterday for [4])?

[1]: https://github.com/opencontainers/runtime-spec/pull/886#event-1157981358
[2]: https://github.com/opencontainers/runtime-spec/milestone/9
[3]: https://github.com/opencontainers/runtime-spec/milestone/16
[4]: https://github.com/opencontainers/runtime-spec/pull/889#event-1187593037

**Pull request merged**
