### PR TITLE
Add go.mod to pin versions

### PR DESCRIPTION
**Pull request by ashokponkumar**
Signed-off-by: Ashok Pon Kumar <ashokponkumar@gmail.com>

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by thaJeztah** [comment]
oh! reminds me I wanted to write a proposal to consider tagging the go implementation separate from the main repository. Doing so would allow doing intermediate releases of the go implementation (fixes in Go that don't affect the runtime spec itself).

If that would be accepted as proposal, I think the `go.mod` should be inside the `spec-go` directory (basically becoming a submodule with its own tag)

**Comment by thaJeztah** [comment]
did a quick write-up; https://github.com/opencontainers/runtime-spec/issues/1069

**Comment by mikebrow** [comment]
> oh! reminds me I wanted to write a proposal to consider tagging the go implementation separate from the main repository. Doing so would allow doing intermediate releases of the go implementation (fixes in Go that don't affect the runtime spec itself).
> 
> If that would be accepted as proposal, I think the `go.mod` should be inside the `spec-go` directory (basically becoming a submodule with its own tag)

Nice.. I was simultaneously thinking the same thing over here: https://github.com/opencontainers/distribution-spec/pull/192#pullrequestreview-500692064

**Comment by vbatts** [comment]
closing in favor of getting a release tagging process in place

**Pull request closed without merging**
