### PR TITLE
schema/config-linux: s/throttleWriteIopsDevice/throttleWriteIOPSDevice/

### PR DESCRIPTION
**Pull request by 0x0916**
Signed-off-by: 0x0916 <w@laoqinren.net>

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

**Comment by 0x0916** [comment]
ping @hqhq @caniszczyk @mrunalp @vbatts @vishh @philips @tianon

**Comment by crosbymichael** [comment]
LGTM

**Comment by crosbymichael** [comment]
@0x0916 thanks!

**Pull request merged**
