### PR TITLE
Add PullApprove checks

### PR DESCRIPTION
**Pull request by crosbymichael**
Add PullApprove: https://pullapprove.com/opencontainers/runtime-spec/

Test for #457 

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
LGTM

**Comment by caniszczyk** [comment]
Thanks @crosbymichael, if this works well I'd like to add it to runc and image-spec

**Comment by crosbymichael** [comment]
LGTM ( wasn't my original commit )

@opencontainers/runtime-spec-maintainers what do you think?  I like it and its simple.

**Comment by mrunalp** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by jfrazelle** [comment]
That is neat!

On Thu, May 26, 2016 at 3:35 PM, Mrunal Patel <notifications@github.com>
wrote:

> LGTM
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencontainers/runtime-spec/pull/458#issuecomment-222014614>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbNGGBKRO7V9n9hheyJLDnqcglTqrks5qFiA0gaJpZM4IoAlF>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by wking** [comment]
Look at all of these people :).  Hopefully the increased review also
applies to spec changes ;).

I don't see markup on commits here like there was in project-template
[1].  Does the config have to land in master first?

[1]: https://github.com/opencontainers/project-template/pull/12#issuecomment-221937899

**Pull request merged**
