### PR TITLE
PullApprove: No need for 3 DCO checks

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by tianon** [comment]
Vigorously,

LGTM

**Comment by cyphar** [comment]
Did you also want to drop the DCO check from `git-validation`?

**Comment by vbatts** [comment]
@cyphar fixed. PTAL

**Comment by cyphar** [comment]
LGTM.

**Comment by tianon** [comment]
LGTM

**Comment by vbatts** [comment]
@cyphar might you remove the trail period in your approval

**Comment by tianon** [comment]
@vbatts he's not a maintainer on the spec 😅

https://pullapprove.com/opencontainers/runtime-spec/pull-request/1029/reviews/

**Comment by vbatts** [comment]
oh! then nm

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tianon** [comment]
cc @opencontainers/runtime-spec-maintainers -- this is an easy one that just needs one more LGTM

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
