### PR TITLE
Fix link on IEEE Std 1003.1-2008

### PR DESCRIPTION
**Pull request by rutsky**
/cc: @wking

### CODE REVIEW

**Comment by wking** [comment]
On Sun, Aug 20, 2017 at 11:01:43PM +0000, Vladimir Rutsky wrote:
> /cc: @wking

Oops, it looks like I broke these in #858.  Sorry about that :/.

Personally, I find “functions” more understandable than “xsh”, so I'd
like to have the link label definition updated to match the reference:

  [ieee-1003.1-2008-functions-exec]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html

(vs. db58e01e5d which updates the reference to match the link label
definition).  But either way would clearly be better than the current
broken link ;).

**Comment by rutsky** [comment]
@wking updated according to your suggestion.

**Comment by hqhq** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
