### PR TITLE
ROADMAP: Remove stale targets (landed PRs, image-spec, ocitools, etc.)

### PR DESCRIPTION
**Pull request by wking**
This PR cherry-picks the first two from #423 and adds additional
target-removal commits with the reasoning I posted [to the list][1].
I'm happy to pull out any contentious and/or obvious commits into
separate PRs if that makes reviewing and landing this easier.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!original/dev/pghr1WFU5KI/NDFTvMDiFAAJ

### CODE REVIEW

**Comment by crosbymichael** [comment]
This did not need to be 6 commits

**Comment by wking** [comment]
On Fri, May 13, 2016 at 01:13:47PM -0700, Michael Crosby wrote:
> This did not need to be 6 commits 

I can squash if you like, but having six commits gave a convenient
place to motivate each removal, and I wasn't sure they would all be
picked up.  If they do all look good and you want me to squash, I can
always use sub-headings in a single commit message.  Just tell me what
you want ;).

**Comment by vbatts** [comment]
Squash them

**Comment by wking** [comment]
On Sun, May 15, 2016 at 11:28:29AM -0700, Vincent Batts wrote:
> Squash them

Squashed with a45289c → 23e03f9.

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
