### PR TITLE
config-solaris: Replaced refs with actual fields in cappedCPU, cappedMemory and anet fields

### PR DESCRIPTION
**Pull request by q384566678**
Signed-off-by: zhouhao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
For posterity sake, it would be nice to have a more detailed submit message.  Perhaps: "config-solaris: Replaced refs with actual fields in cappedCPU, cappedMemory and anet fields"

**Comment by q384566678** [comment]
@dqminh @tianon  @crosbymichael PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by q384566678** [comment]
ping @hqhq

**Comment by hqhq** [comment]
LGTM

**Pull request merged**
