### PR TITLE
Define hook structure clearly and explicitly

### PR DESCRIPTION
**Pull request by WeiZhang555**
Describe the hook structure in a consistent and clear way.

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
ping @vbatts @crosbymichael @hqhq @opencontainers/runtime-spec-maintainers

**Comment by hqhq** [comment]
LGTM

**Comment by wking** [comment]
Overlaps with #427.

**Comment by hqhq** [comment]
Close in favor of #427 .

**Pull request closed without merging**
