### PR TITLE
*: fetch code-of-conduct.md from tob

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
@RobDolinMS this will fix the code of conduct relocation.

This also pins a specifc version of the document, not just master.

**Comment by RobDolinMS** [comment]
I gave the code a quick read and LGTM 👍

**Comment by wking** [comment]
On Fri, Apr 29, 2016 at 11:39:04AM -0700, Vincent Batts wrote:
“This also pins a specifc version of the document, not just master.”

Is there a reason for that?  Folks interested in the history can check
the TOB repo.  Folk interested in applying the code-of-conduct to a
current interaction should be using the current code.

**Comment by crosbymichael** [comment]
LGTM

**Pull request merged**
