### PR TITLE
Remove exec from required runtime functionalities.

### PR DESCRIPTION
**Pull request by vishh**
Exec can be implemented as running additional containers.

For #345

### CODE REVIEW

**Comment by vishh** [comment]
cc @mrunalp @crosbymichael

**Comment by wking** [comment]
On Tue, Apr 19, 2016 at 10:53:58AM -0700, Vish Kannan wrote:
>   * Remove exec from required runtime functionalities. Exec can be

Probably want two newlines instead of the period to avoid the
long-subject error [1].

[1]: https://travis-ci.org/opencontainers/runtime-spec/jobs/124259128#L181

**Comment by wking** [comment]
Do we want to put suggestions about implementing exec in an
informative sections somewhere?  I'd guess the template is:

  {
    "ociVersion": … usual stuff…,
    "platform": … usual stuff…,
    "process": … what you want to exec…,
    "root": what to put here?
    "linux": {
      "cgroupsPath": … extracted from state JSON…,
      "namespaces": [
        {
          "type": "pid",
          "path": … extracted from state JSON…
        },
        …
      ]
    }
  }

The namespace paths and cgroupsPath would come from a procfs entry,
which you'd find by:

1. Get state JSON using the ‘state <container-id>’ operation.
2. Get the container PID from the state (and maybe the process
   namespace that PID is from [1]).
3. Find a procfs mount for the process namespace listed in the state
   JSON [1]).

The namespace paths would be from /proc/{pid}/ns/…, and the
cgroupsPath would be from /proc/self/cgroup (any particular cgroup in
that list?).

Any ideas about ‘root’?

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/ujtABQoCmgk
     Subject: Linux: Adding the PID namespace inode to state JSON
     Date: Wed, 30 Dec 2015 21:34:57 -0800
     Message-ID: <20151231053457.GG3680@odin.tremily.us>

**Comment by crosbymichael** [comment]
LGTM after travis is happy

**Comment by vishh** [comment]
@wking We need blessed cookbook for the Spec.

**Comment by wking** [comment]
On Tue, Apr 19, 2016 at 03:20:51PM -0700, Vish Kannan wrote:
> @wking We need blessed cookbook for the Spec. 

Sounds good to me.  And that can certainly happen in a separate
thread/issue/PR if folks want.  But I think it makes sense to back up
the “can be implemented…” claim with explicit “… and here's how …”
directions in this PR.  There aren't many missing pieces in [1], so it
shouldn't take that much work to clear them up.

[1]: https://github.com/opencontainers/runtime-spec/pull/388#issuecomment-212049907

**Comment by crosbymichael** [comment]
We can work on that stuff later, we just need to get the spec finalized and in good shape before we start talking about how ppl should implement something

**Comment by wking** [comment]
On Tue, Apr 19, 2016 at 04:09:13PM -0700, Michael Crosby wrote:
> We can work on that stuff later, we just need to get the spec
> finalized and in good shape before we start talking about how ppl
> should implement something

Agreed, I just think “in good shape” includes exec-like behavior.  To
avoid reducing functionality with this PR, I think we need to also
fill in the gaps to make ‘exec’ emulation possible.

For example, making ‘root’ optional [1] would be one way to address a
question from [2].  If folks have alternative approaches for handling
that question (supported by the current spec?), that seems like the
sort of thing we want hashed out before we remove the current ‘exec’
feature.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/6ZKMNWujDhU
     Subject: Dropping the rootfs requirement and restoring arbitrary bundle content
     Date: Wed, 26 Aug 2015 12:54:47 -0700
     Message-ID: <20150826195447.GX21585@odin.tremily.us>
[2]: https://github.com/opencontainers/runtime-spec/pull/388#issuecomment-212049907

**Comment by mrunalp** [comment]
@wking I think we can handle examples/cookbook etc. after this PR. To answer your question about `root`, it isn't used in exec if there is a mount namespace.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
